
import React from 'react';
import PageHeader from '@/components/layout/PageHeader';
import { Container } from '@/components/ui/Container';
import { Shield, Book, Lock, RefreshCw, Scale } from 'lucide-react';
import GlassCard from '@/components/ui/GlassCard';

export default function Page() {
  return (
    <main className="bg-white pb-24">
      <PageHeader
        title="Privacy Notice"
        breadcrumb={[
          { label: 'Home', href: '/' },
          { label: 'Privacy Notice', href: '#' }
        ]}
      />
      <Container className="pt-16 pb-24">
        <div className="max-w-4xl mx-auto">
          <GlassCard className="p-8 md:p-12 mb-12 border-l-4 border-l-brand-violet">
            <div className="flex items-start gap-4">
              <Shield className="w-8 h-8 text-brand-violet shrink-0" />
              <div>
                <h2 className="text-2xl font-serif text-brand-violet mb-4">Our Commitment</h2>
                <p className="text-lg text-slate-600 font-light leading-relaxed">
                  This document constitutes the Privacy Notice for the purposes of the provisions of the <strong>Federal Law on Protection of Personal Data Held by Private Parties</strong> in force. This Notice applies to personal information collected about the Data Subject by <strong>Fertility Center Cancun, S.A.P.I. de C.V.</strong>, in its capacity as Data Controller.
                </p>
              </div>
            </div>
          </GlassCard>

          <div className="grid gap-8">
            <section>
              <h3 className="text-2xl font-serif text-brand-violet mb-6 flex items-center gap-3">
                <Book className="w-6 h-6" />
                1. Key Definitions
              </h3>
              <div className="grid gap-4">
                {[
                  { title: "Privacy Notice", desc: "Physical or electronic document generated by the controller and made available to the data subject." },
                  { title: "Personal Data", desc: "Any information concerning an identified or identifiable natural person." },
                  { title: "Sensitive Personal Data", desc: "Data that affects the most intimate sphere of the data subject or whose misuse may give rise to discrimination." },
                  { title: "ARCO Rights", desc: "Means the rights of Access, Rectification, Cancellation, and Opposition." }
                ].map((item, i) => (
                  <div key={i} className="bg-slate-50 p-6 rounded-2xl border border-slate-100 hover:border-brand-violet/20 transition-colors">
                    <h4 className="font-bold text-brand-violet mb-1">{item.title}</h4>
                    <p className="text-slate-600 font-light">{item.desc}</p>
                  </div>
                ))}
              </div>
            </section>

            <section className="bg-brand-violet rounded-[3rem] p-10 text-white shadow-xl my-8">
              <h3 className="text-3xl font-serif mb-8 flex items-center gap-3">
                <Lock className="w-8 h-8 text-brand-green" />
                2. ARCO Rights
              </h3>
              <div className="grid md:grid-cols-2 gap-8">
                <div>
                  <h4 className="font-bold text-brand-green mb-2">Access and Rectification</h4>
                  <p className="font-light opacity-90">You have the right to know what personal data we hold, how we use it, and the conditions of use. Likewise, you have the right to request the correction of your personal information if it is outdated, inaccurate, or incomplete.</p>
                </div>
                <div>
                  <h4 className="font-bold text-brand-green mb-2">Cancellation and Opposition</h4>
                  <p className="font-light opacity-90">You have the right to have your information deleted from our records or databases when you consider it is not being used properly. You may also oppose the use of your personal data for specific purposes.</p>
                </div>
              </div>
            </section>

            <section>
              <h3 className="text-2xl font-serif text-brand-violet mb-6 flex items-center gap-3">
                <Scale className="w-6 h-6" />
                3. Purpose of Data Processing
              </h3>
              <GlassCard className="p-8">
                <ul className="grid md:grid-cols-2 gap-4 list-none p-0">
                  {[
                    "Provision of medical-hospital services",
                    "Health information studies and analysis",
                    "Billing and collection for services",
                    "Statistical and market analysis",
                    "Follow-up on future services",
                    "Clinical record maintenance"
                  ].map((text, i) => (
                    <li key={i} className="flex items-center gap-3 text-slate-700">
                      <div className="w-2 h-2 rounded-full bg-brand-green shrink-0" />
                      <span className="font-light">{text}</span>
                    </li>
                  ))}
                </ul>
              </GlassCard>
            </section>

            <section className="bg-brand-gray p-8 rounded-[2.5rem] border border-brand-violet/10 mt-8 text-center">
              <RefreshCw className="w-10 h-10 text-brand-violet mx-auto mb-4 opacity-50" />
              <h3 className="text-xl font-bold text-brand-violet mb-2">Changes to This Notice</h3>
              <p className="text-slate-600 font-light italic">
                We reserve the right to periodically update this Privacy Notice. It is the Data Subject&apos;s responsibility to review the content on our website <a href="https://fcc.com.mx" className="text-brand-violet font-bold hover:underline">www.fcc.com.mx</a>.
              </p>
            </section>
          </div>
        </div>
      </Container>
    </main>
  );
}
